Repository rueckstiess/mtools, pull requests merged in 2018-04, with the labels that each got.

#585 Join paths correctly for OS
  mtools/mlaunch/mlaunch.py
Labels: mlaunch

#588 Fix #587: Add py36 environment for tox & Travis
  .travis.yml
  tox.ini
Labels: tests

#591 Fix #590: mlaunch: Update psutil requirement to 5.4.2
  requirements.txt
  setup.py
Labels: improvement, mlaunch

#583 Handle spaces in mlaunch `binarypath` parameter in Unix and Windows.
  mtools/mlaunch/mlaunch.py
  mtools/test/test_mlaunch_commandlines.py
Labels: bug, mlaunch

#594 Fix #593: Update CHANGES.rst for 1.4.0 release
  CHANGES.rst
Labels: task
